'use strict';

const logger = require('./logger');

// ─────────────────────────────────────────────────────────────────────────────
// Windows PowerShell script
// Uses array-join instead of template literals to avoid backtick/$ conflicts
// between JavaScript template syntax and PowerShell syntax.
// ─────────────────────────────────────────────────────────────────────────────

function generateWindowsScript(parsedCommand, softwareNames) {
  const { action, osCommands, verify } = parsedCommand;
  const win = osCommands?.windows || {};

  const cmds = [
    ...(win.preCommands  || []),
    ...(win.commands     || []),
    ...(win.postCommands || []),
  ];

  const verifyCmds = verify?.commands || [];

  // Escape double-quotes for embedding inside a PS double-quoted string
  const psEsc = s => s.replace(/"/g, '`"');

  const lines = [
    '#Requires -RunAsAdministrator',
    '<#',
    '  Auto-generated by Installer Manager Backend',
    '  Action   : ' + action.toUpperCase(),
    '  Software : ' + softwareNames.join(', '),
    '  Generated: ' + new Date().toISOString(),
    '#>',
    '',
    "$ErrorActionPreference = 'Stop'",
    '',
    'function Invoke-Step {',
    '    param([string]$Desc, [string]$Cmd)',
    '    Write-Host "`n>>> $Desc" -ForegroundColor Cyan',
    '    Write-Host "    $Cmd"   -ForegroundColor DarkGray',
    '    Invoke-Expression $Cmd',
    '    if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {',
    '        throw "Step failed (exit $LASTEXITCODE): $Cmd"',
    '    }',
    '    Write-Host "    OK" -ForegroundColor Green',
    '}',
    '',
    'Write-Host "===  Installer Manager  ===" -ForegroundColor Yellow',
    'Write-Host "Action  : ' + action.toUpperCase() + '"',
    'Write-Host "Software: ' + softwareNames.join(', ') + '"',
    '',
    'try {',
    ...cmds.map((c, i) => '    Invoke-Step "Step ' + (i + 1) + '" "' + psEsc(c) + '"'),
  ];

  if (verifyCmds.length > 0) {
    lines.push('    Write-Host "`n=== Verification ===" -ForegroundColor Yellow');
    for (const c of verifyCmds) {
      lines.push('    Write-Host "  ' + psEsc(c) + '" -ForegroundColor DarkGray');
      lines.push('    Invoke-Expression "' + psEsc(c) + '"');
    }
  }

  lines.push(
    '    Write-Host "`n=== COMPLETED SUCCESSFULLY ===" -ForegroundColor Green',
    '} catch {',
    '    Write-Host "`n=== FAILED ===" -ForegroundColor Red',
    '    Write-Host $_.Exception.Message -ForegroundColor Red',
    '    exit 1',
    '}'
  );

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Linux / macOS shell script
// ─────────────────────────────────────────────────────────────────────────────

function generateShellScript(parsedCommand, softwareNames, targetOS = 'linux') {
  const { action, osCommands, verify } = parsedCommand;
  const osKey = targetOS === 'macos' ? 'macos' : 'linux';
  const block  = osCommands?.[osKey] || {};

  const cmds = [
    ...(block.preCommands  || []),
    ...(block.commands     || []),
    ...(block.postCommands || []),
  ];

  const verifyCmds = verify?.commands || [];

  // Escape double-quotes for embedding in a bash double-quoted context
  const shEsc = s => s.replace(/"/g, '\\"');

  const lines = [
    '#!/usr/bin/env bash',
    '# Auto-generated by Installer Manager Backend',
    '# Action   : ' + action.toUpperCase(),
    '# Software : ' + softwareNames.join(', '),
    '# Generated: ' + new Date().toISOString(),
    '# Usage    : sudo bash <this-script>',
    '',
    'set -euo pipefail',
    '',
    "RED='\\033[0;31m'; GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; CYAN='\\033[0;36m'; NC='\\033[0m'",
    '',
    'step() {',
    '  local n="$1"; local cmd="$2"',
    '  echo -e "\\n${CYAN}>>> $n${NC}"',
    '  echo -e "    ${cmd}"',
    '  eval "$cmd"',
    '  echo -e "    ${GREEN}OK${NC}"',
    '}',
    '',
    'echo -e "${YELLOW}=== Installer Manager ===${NC}"',
    'echo "Action  : ' + action.toUpperCase() + '"',
    'echo "Software: ' + softwareNames.join(', ') + '"',
    '',
    ...cmds.map((c, i) => 'step "Step ' + (i + 1) + '" "' + shEsc(c) + '"'),
  ];

  if (verifyCmds.length > 0) {
    lines.push('', 'echo -e "\\n${YELLOW}=== Verification ===${NC}"');
    for (const c of verifyCmds) {
      lines.push('echo "  ' + shEsc(c) + '"');
      lines.push('eval "' + shEsc(c) + '"');
    }
  }

  lines.push('', 'echo -e "\\n${GREEN}=== COMPLETED SUCCESSFULLY ===${NC}"');

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Public: pick correct generator and return structured fallback response
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate an OS-appropriate fallback script when remote execution fails.
 * Returns the object that routes.js sends back to the API caller.
 */
function generateFallbackScript(parsedCommand, machineInfo) {
  const { os = 'windows', hostname } = machineInfo;
  const names = parsedCommand.displayNames || parsedCommand.software || ['unknown'];

  logger.info('Generating fallback script', { os, software: names });

  const slug = names.join('-').replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  const ts   = Date.now();

  if (os === 'windows') {
    return {
      status:       'fallback',
      os:           'windows',
      filename:     'install-' + slug + '-' + ts + '.ps1',
      contentType:  'application/x-powershell',
      script:       generateWindowsScript(parsedCommand, names),
      instructions: [
        'Save the script content to a .ps1 file, e.g. C:\\install-' + slug + '.ps1',
        'Open PowerShell as Administrator on ' + hostname,
        'Run: Set-ExecutionPolicy Bypass -Scope Process -Force',
        'Run: .\\install-' + slug + '.ps1',
        'Check the output for errors.',
      ],
    };
  }

  return {
    status:       'fallback',
    os,
    filename:     'install-' + slug + '-' + ts + '.sh',
    contentType:  'application/x-sh',
    script:       generateShellScript(parsedCommand, names, os),
    instructions: [
      'Save the script content to a file, e.g. /tmp/install-' + slug + '.sh',
      'Make it executable: chmod +x /tmp/install-' + slug + '.sh',
      'Run with elevated privileges: sudo bash /tmp/install-' + slug + '.sh',
      'Check the output for errors.',
    ],
  };
}

module.exports = { generateWindowsScript, generateShellScript, generateFallbackScript };
